name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Nim environment (1.4.0)
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 1.4.0
    
      - name: Fix apt packages
        run: |
          # see. https://github.com/actions/virtual-environments/issues/675
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo apt update -yqq

      - name: Install sdl2
        run: sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev

      - name: Install packages
        run: nimble install -Y
        
      - name: Build
        run: |
          nimble release
          nimble web

      - name: Test
        run: nimble test

